#!/bin/sh

script=`which $0`
scriptdir=`dirname $0`

ppfiles=""
doremove=0
if [ -d $scriptdir/connectal ]; then
    for f in $*; do
	$scriptdir/connectal/scripts/bsvpreprocess.py -I$scriptdir -I. $f > $f.pp
	ppfiles="$ppfiles $f.pp"
    done
    doremove=0
else
    ppfiles="$*"
fi
echo java
time java -classpath $scriptdir/build/libs/bsvtokami.jar:$scriptdir/jars/antlr-4.7.1-complete.jar org.antlr.v4.gui.TestRig BSV packagedef $ppfiles
# echo c++
# time $scriptdir/bin/bsv-parser-cpp $ppfiles

if [ "$doremove" = "1" ]; then
    rm -f $ppfiles
fi
