#!/bin/bash

script=`which $0`
scriptdir=`dirname $0`

ppfiles=""
doremove=0
if [ -d $scriptdir/connectal ]; then
    for f in $*; do
	$scriptdir/connectal/scripts/bsvpreprocess.py -I$scriptdir -I. $f > $f.pp
	ppfiles="$ppfiles $f.pp"
    done
    doremove=1
else
    ppfiles="$*"
fi
java -classpath $scriptdir/classes:$scriptdir/jars/antlr-4.7.1-complete.jar Main $ppfiles

if [ "$doremove" = "1" ]; then
    rm -f $ppfiles
fi
