#!/bin/bash

script=`which $0`
scriptdir=`dirname $0`

ppfiles=""
doremove=0

export BSVSEARCHPATH="$scriptdir/lib"
for d in $BLUESPECDIR/BSVSource/*; do
    BSVSEARCHPATH="$BSVSEARCHPATH:$d"
done
echo BSVSEARCHPATH="$BSVSEARCHPATH"

if [ -d $scriptdir/connectal ]; then
    for f in $*; do
	fdir=`dirname $f`
	$scriptdir/connectal/scripts/bsvpreprocess.py -I$fdir -I$scriptdir -I. $f > $f.pp
	ppfiles="$ppfiles $f.pp"
    done
    doremove=0
else
    ppfiles="$*"
fi
java -ea -classpath $scriptdir/classes:$scriptdir/jars/antlr-4.7.1-complete.jar Main $ppfiles

if [ "$doremove" = "1" ]; then
    rm -f $ppfiles
fi
