#!/bin/bash

script=`which $0`
scriptdir=`dirname $0`

ppfiles=""
doremove=0

export BSVSEARCHPATH="$scriptdir/lib"
for f in $*; do
    if [ -d $f ]; then
	BSVSEARCHPATH="$BSVSEARCHPATH:$f"
    fi
done
for d in $BLUESPECDIR/BSVSource/*; do
    BSVSEARCHPATH="$BSVSEARCHPATH:$d"
done
echo BSVSEARCHPATH="$BSVSEARCHPATH"

if [ -d $scriptdir/connectal ]; then
    for f in $*; do
	if [ -d $f ]; then
	    true
	elif [ -f $f ]; then
	    fdir=`dirname $f`
	    $scriptdir/connectal/scripts/bsvpreprocess.py -DBSVTOKAMI -I$fdir -I$scriptdir -I. $f > $f.pp
	    ppfiles="$ppfiles $f.pp"
	fi
    done
    doremove=0
    ppfiles="$*"
else
    ppfiles="$*"
fi
java -ea -classpath $scriptdir/classes:$scriptdir/jars/antlr-4.7.1-complete.jar Main $ppfiles

if [ "$doremove" = "1" ]; then
    rm -f $ppfiles
fi
